### ISSUE TITLE
我发现了一个无关紧要的问题

### ISSUE THREAD

**Issue by hellojukay** [tabalt/pmon#1]
https://github.com/tabalt/pmon/blob/c7d959a7406ff4be521cafca0bed85567532bfbe/pmon.go#L76
这行代码似乎永远也不会执行，所以是不是可以删除https://github.com/tabalt/pmon/blob/c7d959a7406ff4be521cafca0bed85567532bfbe/pmon.go#L33
这个也是在循环的第一次的时候就阻塞了，然后程序就永远都不会退出（这是你们的目的）

**Comment by tabalt** [comment]
这两处代码是配合使用的，目的是当所有的协程都退出后主程序才退出，算是一个常用实践。
从目前monitorProcess函数的逻辑代码表面看，确实不会出现协程退出的情况，但是后续有可能会添加异常退出的代码，因此这两处逻辑不可以删除。
